### ISSUE TITLE
Missing Java transaction setMasterInvoiceLineReferences()

### ISSUE THREAD

**Issue by norbertbede** [bxservice/de.bxservice.relatedproduct#1]
https://github.com/bxservice/de.bxservice.relatedproduct/blob/57e68135c25409c6dd1c09c1eb77de03be9cffa5/src/de/bxservice/model/ValidatorRelatedProduct.java#L433

```
-MOrderLine referencedOrderLine = new MOrderLine(Env.getCtx(), invoiceLine.getC_OrderLine_ID(), null);
+MOrderLine referencedOrderLine = new MOrderLine(Env.getCtx(), invoiceLine.getC_OrderLine_ID(), invoice.get_TrxName());
```

**Comment by d-ruiz** [comment]
Thanks @norbertbede - fuixed: https://github.com/bxservice/de.bxservice.relatedproduct/commit/5cc69eb47c030aadc5dfe25df0f6e214a394b5b9
